package com.example.ava.Model;

public class Enums {
    public enum Etat {
        Attente, Actif, Refuse, Archive, Cloture, Suspendu
    }

    public enum Secteur {
        EXPORT,
        PROFESSION_LIBERALE,
        ETUDES_ET_CONSEILS,
        SERVICES_INFORMATIQUES,
        PROMOTION_IMMOBILIERE,
        TRAVAUX_PUBLICS_ET_BATIMENT,
        TRANSPORT_INTERNATIONAL_ROUTIER_DE_MARCHANDISES,
        CONSIGNATION_DE_NAVIRES,
        TRANSITAIRES,
        PRODUCTION_ET_DISTRIBUTION_CINEMATOGRAPHIQUE,
        IMPRESSION_ET_EDITION,
        PUBLICITE_ET_COMMUNICATION,
        ASSURANCES,
        AGENCES_DE_VOYAGES_LICENCE_A,
        ENSEIGNEMENT_SUPERIEUR_PRIVE,
        CLINIQUES_PRIVEES,
        LABORATOIRES_D_ANALYSES,
        SERVICES_FINANCIERS_BANQUE_LEASING,
        BOURSE_DES_VALEURS_MOBILIERES,
        INTERMEDIAIRES_EN_BOURSE,
        ANESTHESIE_ET_REANIMATION,
        OBSTETRIQUE,
        PSYCHIATRIE,
        PHYSIOTHERAPIE,
        ERGOTHERAPIE,
        ORTHOPHONIE,
        ORTHOPTIE,
        PROTHESE
    }

}
